name: Formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Run gofmt
      run: go fmt ./...
    
    - name: Run gofumpt
      run: |
        go install mvdan.cc/gofumpt@latest
        export PATH=${PATH}:`go env GOPATH`/bin
        gofumpt -l -extra -w .
      
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git checkout ${{ github.event.pull_request.head }}
          git commit -am "Automated changes"
          git push
